[UI]

name = "Ask Parth AI"

description = "Ask about my experience, projects, and technical background."

default_theme = "dark"

layout = "wide"

default_sidebar_state = "hidden"

cot = "hidden"

logo_file_url = "/public/favicon.png"

default_avatar_file_url = "/public/favicon.png"