[project]

user_env = []

session_timeout = 3600

user_session_timeout = 1296000

cache = false

persist_user_env = false

mask_user_env = false

allow_origins = ["*"]


[features]

unsafe_allow_html = false

latex = false

user_message_markdown = true

user_message_autoscroll = true

assistant_message_autoscroll = true

auto_tag_thread = true

edit_message = true

allow_thread_sharing = false

favorites = false


[features.slack]

reaction_on_message_received = false


[features.spontaneous_file_upload]

enabled = false

accept = [
    "application/pdf",
    "image/png",
    "image/jpeg"
]

max_files = 5

max_size_mb = 50


[features.audio]

enabled = false

sample_rate = 24000


[features.mcp]

enabled = false


[features.mcp.sse]

enabled = true


[features.mcp.streamable-http]

enabled = true


[features.mcp.stdio]

enabled = true

allowed_executables = [
    "npx",
    "uvx"
]


[UI]

# Assistant name shown in the app
name = "Ask Parth AI"

# Dark ChatGPT style
default_theme = "dark"

# Desktop layout
layout = "wide"

# Hide sidebar
default_sidebar_state = "hidden"

# New chat confirmation
confirm_new_chat = false

# App description
description = "Ask about my experience, projects, and technical background."

# Hide Chainlit chain of thought UI
cot = "hidden"

# Your favicon/logo
logo_file_url = "/public/favicon.png"

# Assistant avatar
default_avatar_file_url = "https://img.icons8.com/color/96/ai-robot--v15.png"

avatar_size = 32

# Custom CSS if needed later
custom_css = "/public/custom.css"

alert_style = "modern"

header_links = [
  {
    name = "LinkedIn",
    icon_url = "https://img.icons8.com/fluency/96/linkedin.png",
    url = "https://www.linkedin.com/in/parikhparth23"
  },
  {
    name = "GitHub",
    icon_url = "https://img.icons8.com/color-glass/96/github--v1.png",
    url = "https://github.com/parikhparth23"
  },
  {
    name = "Email",
    icon_url = "https://img.icons8.com/fluency/96/email-open.png",
    url = "mailto:parikhparth23@gmail.com"
  },
]

[meta]

generated_by = "2.11.0"
